package com.station.moudles.entity;

import java.math.BigDecimal;
import java.util.Date;

import org.hibernate.validator.constraints.NotEmpty;

import com.fasterxml.jackson.annotation.JsonFormat;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * This class was generated by Bill Generator.
 * This class corresponds to the database table gprs_config_send  基站gprs参数配置表
 *
 * @zdmgenerated 2017-13-19 07:13
 */
@ApiModel(value = "基站gprs参数配置表", description = "基站gprs参数配置表描述")
public class GprsConfigSend {
	/**
	 * This field corresponds to the database column gprs_config_send.id  
	 */
	@ApiModelProperty(value = "pk", required = true)
	private Integer id;

	/**
	 * This field corresponds to the database column gprs_config_send.gprs_id  
	 */
	@ApiModelProperty(value = "gprsId", example = "gprsId", required = false)
	private String gprsId;

	/**
	 * This field corresponds to the database column gprs_config_send.insert_time  
	 */
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
	@ApiModelProperty(value = "insertTime")
	private Date insertTime;

	/**
	 * This field corresponds to the database column gprs_config_send.connection_type  连接属性-> 1：短连接，无需保活帧；2：长连接，需要保活帧
	 */
	@ApiModelProperty(value = "连接属性-> 1：短连接，无需保活帧；2：长连接，需要保活帧", required = false)
	private Integer connectionType;

	/**
	 * This field corresponds to the database column gprs_config_send.heartbeat_interval  心跳间隔，如果为0则为短链接,单位秒
	 */
	@ApiModelProperty(value = "心跳间隔，如果为0则为短链接,单位秒", required = false)
	private Integer heartbeatInterval;

	/**
	 * This field corresponds to the database column gprs_config_send.float_interval  浮充状态下状态帧传输间隔，单位秒
	 */
	@ApiModelProperty(value = "浮充状态下状态帧传输间隔，单位秒", required = false)
	private Integer floatInterval;

	/**
	 * This field corresponds to the database column gprs_config_send.discharge_interval  放电状态下状态帧传输间隔，单位秒
	 */
	@ApiModelProperty(value = "放电状态下状态帧传输间隔，单位秒", required = false)
	private Integer dischargeInterval;

	/**
	 * This field corresponds to the database column gprs_config_send.charge_threshold  充电判断阈值，单位V
	 */
	@ApiModelProperty(value = "充电判断阈值，单位V", required = false)
	private BigDecimal chargeThreshold;

	/**
	 * This field corresponds to the database column gprs_config_send.discharge_threshold  放电判断阈值
	 */
	@ApiModelProperty(value = "放电判断阈值", required = false)
	private BigDecimal dischargeThreshold;

	/**
	 * This field corresponds to the database column gprs_config_send.nominal_capacity  电池容量 Ah
	 */
	@ApiModelProperty(value = "电池容量 Ah", required = false)
	private BigDecimal nominalCapacity;

	/**
	 * This field corresponds to the database column gprs_config_send.current_capacity  电池当前容量 Ah
	 */
	@ApiModelProperty(value = "电池当前容量 Ah", required = false)
	private BigDecimal currentCapacity;

	/**
	 * This field corresponds to the database column gprs_config_send.vol_high_warning_threshold  总电压过高告警阈值,V
	 */
	@ApiModelProperty(value = "总电压过高告警阈值,V", required = false)
	private BigDecimal volHighWarningThreshold;

	/**
	 * This field corresponds to the database column gprs_config_send.vol_low_warning_threshold  总电压过低告警阈值 V
	 */
	@ApiModelProperty(value = "总电压过低告警阈值 V", required = false)
	private BigDecimal volLowWarningThreshold;

	/**
	 * This field corresponds to the database column gprs_config_send.tem_high_warning_threshold  温度过高告警阈值 ℃
	 */
	@ApiModelProperty(value = "温度过高告警阈值 ℃", required = false)
	private Integer temHighWarningThreshold;

	/**
	 * This field corresponds to the database column gprs_config_send.tem_low_warning_threshold  温度过低告警阈值
	 */
	@ApiModelProperty(value = "温度过低告警阈值", required = false)
	private Integer temLowWarningThreshold;

	/**
	 * This field corresponds to the database column gprs_config_send.soc_low_warning_threshold  SOC过低告警阈值
	 */
	@ApiModelProperty(value = "SOC过低告警阈值", required = false)
	private Integer socLowWarningThreshold;

	/**
	 * This field corresponds to the database column gprs_config_send.send_done  命令状态:0未发送,1发送成功，2执行成功，3执行失败
	 */
	@ApiModelProperty(value = "命令状态:0未发送,1发送成功，2执行成功，3执行失败", required = false)
	private Byte sendDone;
	
	/**
     * 电流异常告警上限
     */
    @NotEmpty
    private BigDecimal currentWarningToplimit;

    /**
     * 电流异常告警下限
     */
    @NotEmpty
    private BigDecimal currentWarningLowerlimit;

    /**
     * 单体过压告警阈值
     */
    @NotEmpty
    private BigDecimal singleHighVolThreshold;

    /**
     * 单体欠压告警阈值
     */
    @NotEmpty
    private BigDecimal singleLowVolThreshold;

    /**
     * 总电压过压恢复点
     */
    @NotEmpty
    private BigDecimal highVolRecover;

    /**
     * 总电压欠压恢复点
     */
    @NotEmpty
    private BigDecimal lowVolRecover;

    /**
     * 单体过压恢复点
     */
    @NotEmpty
    private BigDecimal singleHighVolRecover;

    /**
     * 单体欠压恢复点
     */
    @NotEmpty
    private BigDecimal singleLowVolRecover;

    /**
     * 环境高温告警阈值
     */
    @NotEmpty
    private Integer highSurroundingtemWarningThreshold;

    /**
     * 环境低温告警阈值
     */
    @NotEmpty
    private Integer lowSurroundingtemWarningThreshold;

    /**
     * 环境高温告警恢复点
     */
    @NotEmpty
    private Integer highSurroundingtemWarningRecover;

    /**
     * 环境低温告警恢复点
     */
    @NotEmpty
    private Integer lowSurroundingtemWarningRecover;

    /**
     * 单体高温告警恢复点
     */
    @NotEmpty
    private Integer hightemWarningRecover;

    /**
     * 单体低温告警恢复点
     */
    @NotEmpty
    private Integer lowtemWarningRecover;

    /**
     * soc过低
     */
    @NotEmpty
    private Integer lowSocRecover;
	
	//充电状态下状态帧传输间隔，单位秒
    private Integer chargeInterval;

	public Integer getChargeInterval() {
		return chargeInterval;
	}

	public void setChargeInterval(Integer chargeInterval) {
		this.chargeInterval = chargeInterval;
	}

	/**
	 * This method returns the value of the database column gprs_config_send.id  
	 * @return the value of gprs_config_send.id
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method sets the value of the database column gprs_config_send.id  
	 * @param id the value for gprs_config_send.id
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method returns the value of the database column gprs_config_send.gprs_id  
	 * @return the value of gprs_config_send.gprs_id
	 */
	public String getGprsId() {
		return gprsId;
	}

	/**
	 * This method sets the value of the database column gprs_config_send.gprs_id  
	 * @param gprsId the value for gprs_config_send.gprs_id
	 */
	public void setGprsId(String gprsId) {
		this.gprsId = gprsId == null ? null : gprsId.trim();
	}

	/**
	 * This method returns the value of the database column gprs_config_send.insert_time  
	 * @return the value of gprs_config_send.insert_time
	 */
	public Date getInsertTime() {
		return insertTime;
	}

	/**
	 * This method sets the value of the database column gprs_config_send.insert_time  
	 * @param insertTime the value for gprs_config_send.insert_time
	 */
	public void setInsertTime(Date insertTime) {
		this.insertTime = insertTime;
	}

	/**
	 * This method returns the value of the database column gprs_config_send.connection_type  连接属性-> 1：短连接，无需保活帧；2：长连接，需要保活帧
	 * @return the value of gprs_config_send.connection_type
	 */
	public Integer getConnectionType() {
		return connectionType;
	}

	/**
	 * This method sets the value of the database column gprs_config_send.connection_type  连接属性-> 1：短连接，无需保活帧；2：长连接，需要保活帧
	 * @param connectionType the value for gprs_config_send.connection_type
	 */
	public void setConnectionType(Integer connectionType) {
		this.connectionType = connectionType;
	}

	/**
	 * This method returns the value of the database column gprs_config_send.heartbeat_interval  心跳间隔，如果为0则为短链接,单位秒
	 * @return the value of gprs_config_send.heartbeat_interval
	 */
	public Integer getHeartbeatInterval() {
		return heartbeatInterval;
	}

	/**
	 * This method sets the value of the database column gprs_config_send.heartbeat_interval  心跳间隔，如果为0则为短链接,单位秒
	 * @param heartbeatInterval the value for gprs_config_send.heartbeat_interval
	 */
	public void setHeartbeatInterval(Integer heartbeatInterval) {
		this.heartbeatInterval = heartbeatInterval;
	}

	/**
	 * This method returns the value of the database column gprs_config_send.float_interval  浮充状态下状态帧传输间隔，单位秒
	 * @return the value of gprs_config_send.float_interval
	 */
	public Integer getFloatInterval() {
		return floatInterval;
	}

	/**
	 * This method sets the value of the database column gprs_config_send.float_interval  浮充状态下状态帧传输间隔，单位秒
	 * @param floatInterval the value for gprs_config_send.float_interval
	 */
	public void setFloatInterval(Integer floatInterval) {
		this.floatInterval = floatInterval;
	}

	/**
	 * This method returns the value of the database column gprs_config_send.discharge_interval  放电状态下状态帧传输间隔，单位秒
	 * @return the value of gprs_config_send.discharge_interval
	 */
	public Integer getDischargeInterval() {
		return dischargeInterval;
	}

	/**
	 * This method sets the value of the database column gprs_config_send.discharge_interval  放电状态下状态帧传输间隔，单位秒
	 * @param dischargeInterval the value for gprs_config_send.discharge_interval
	 */
	public void setDischargeInterval(Integer dischargeInterval) {
		this.dischargeInterval = dischargeInterval;
	}

	/**
	 * This method returns the value of the database column gprs_config_send.charge_threshold  充电判断阈值，单位V
	 * @return the value of gprs_config_send.charge_threshold
	 */
	public BigDecimal getChargeThreshold() {
		return chargeThreshold;
	}

	/**
	 * This method sets the value of the database column gprs_config_send.charge_threshold  充电判断阈值，单位V
	 * @param chargeThreshold the value for gprs_config_send.charge_threshold
	 */
	public void setChargeThreshold(BigDecimal chargeThreshold) {
		this.chargeThreshold = chargeThreshold;
	}

	/**
	 * This method returns the value of the database column gprs_config_send.discharge_threshold  放电判断阈值
	 * @return the value of gprs_config_send.discharge_threshold
	 */
	public BigDecimal getDischargeThreshold() {
		return dischargeThreshold;
	}

	/**
	 * This method sets the value of the database column gprs_config_send.discharge_threshold  放电判断阈值
	 * @param dischargeThreshold the value for gprs_config_send.discharge_threshold
	 */
	public void setDischargeThreshold(BigDecimal dischargeThreshold) {
		this.dischargeThreshold = dischargeThreshold;
	}

	/**
	 * This method returns the value of the database column gprs_config_send.nominal_capacity  电池容量 Ah
	 * @return the value of gprs_config_send.nominal_capacity
	 */
	public BigDecimal getNominalCapacity() {
		return nominalCapacity;
	}

	/**
	 * This method sets the value of the database column gprs_config_send.nominal_capacity  电池容量 Ah
	 * @param nominalCapacity the value for gprs_config_send.nominal_capacity
	 */
	public void setNominalCapacity(BigDecimal nominalCapacity) {
		this.nominalCapacity = nominalCapacity;
	}

	/**
	 * This method returns the value of the database column gprs_config_send.current_capacity  电池当前容量 Ah
	 * @return the value of gprs_config_send.current_capacity
	 */
	public BigDecimal getCurrentCapacity() {
		return currentCapacity;
	}

	/**
	 * This method sets the value of the database column gprs_config_send.current_capacity  电池当前容量 Ah
	 * @param currentCapacity the value for gprs_config_send.current_capacity
	 */
	public void setCurrentCapacity(BigDecimal currentCapacity) {
		this.currentCapacity = currentCapacity;
	}

	/**
	 * This method returns the value of the database column gprs_config_send.vol_high_warning_threshold  总电压过高告警阈值,V
	 * @return the value of gprs_config_send.vol_high_warning_threshold
	 */
	public BigDecimal getVolHighWarningThreshold() {
		return volHighWarningThreshold;
	}

	/**
	 * This method sets the value of the database column gprs_config_send.vol_high_warning_threshold  总电压过高告警阈值,V
	 * @param volHighWarningThreshold the value for gprs_config_send.vol_high_warning_threshold
	 */
	public void setVolHighWarningThreshold(BigDecimal volHighWarningThreshold) {
		this.volHighWarningThreshold = volHighWarningThreshold;
	}

	/**
	 * This method returns the value of the database column gprs_config_send.vol_low_warning_threshold  总电压过低告警阈值 V
	 * @return the value of gprs_config_send.vol_low_warning_threshold
	 */
	public BigDecimal getVolLowWarningThreshold() {
		return volLowWarningThreshold;
	}

	/**
	 * This method sets the value of the database column gprs_config_send.vol_low_warning_threshold  总电压过低告警阈值 V
	 * @param volLowWarningThreshold the value for gprs_config_send.vol_low_warning_threshold
	 */
	public void setVolLowWarningThreshold(BigDecimal volLowWarningThreshold) {
		this.volLowWarningThreshold = volLowWarningThreshold;
	}

	/**
	 * This method returns the value of the database column gprs_config_send.tem_high_warning_threshold  温度过高告警阈值 ℃
	 * @return the value of gprs_config_send.tem_high_warning_threshold
	 */
	public Integer getTemHighWarningThreshold() {
		return temHighWarningThreshold;
	}

	/**
	 * This method sets the value of the database column gprs_config_send.tem_high_warning_threshold  温度过高告警阈值 ℃
	 * @param temHighWarningThreshold the value for gprs_config_send.tem_high_warning_threshold
	 */
	public void setTemHighWarningThreshold(Integer temHighWarningThreshold) {
		this.temHighWarningThreshold = temHighWarningThreshold;
	}

	/**
	 * This method returns the value of the database column gprs_config_send.tem_low_warning_threshold  温度过低告警阈值
	 * @return the value of gprs_config_send.tem_low_warning_threshold
	 */
	public Integer getTemLowWarningThreshold() {
		return temLowWarningThreshold;
	}

	/**
	 * This method sets the value of the database column gprs_config_send.tem_low_warning_threshold  温度过低告警阈值
	 * @param temLowWarningThreshold the value for gprs_config_send.tem_low_warning_threshold
	 */
	public void setTemLowWarningThreshold(Integer temLowWarningThreshold) {
		this.temLowWarningThreshold = temLowWarningThreshold;
	}

	/**
	 * This method returns the value of the database column gprs_config_send.soc_low_warning_threshold  SOC过低告警阈值
	 * @return the value of gprs_config_send.soc_low_warning_threshold
	 */
	public Integer getSocLowWarningThreshold() {
		return socLowWarningThreshold;
	}

	/**
	 * This method sets the value of the database column gprs_config_send.soc_low_warning_threshold  SOC过低告警阈值
	 * @param socLowWarningThreshold the value for gprs_config_send.soc_low_warning_threshold
	 */
	public void setSocLowWarningThreshold(Integer socLowWarningThreshold) {
		this.socLowWarningThreshold = socLowWarningThreshold;
	}

	/**
	 * This method returns the value of the database column gprs_config_send.send_done  命令状态:0未发送,1发送成功，2执行成功，3执行失败
	 * @return the value of gprs_config_send.send_done
	 */
	public Byte getSendDone() {
		return sendDone;
	}

	/**
	 * This method sets the value of the database column gprs_config_send.send_done  命令状态:0未发送,1发送成功，2执行成功，3执行失败
	 * @param sendDone the value for gprs_config_send.send_done
	 */
	public void setSendDone(Byte sendDone) {
		this.sendDone = sendDone;
	}

	public BigDecimal getCurrentWarningToplimit() {
		return currentWarningToplimit;
	}

	public void setCurrentWarningToplimit(BigDecimal currentWarningToplimit) {
		this.currentWarningToplimit = currentWarningToplimit;
	}

	public BigDecimal getCurrentWarningLowerlimit() {
		return currentWarningLowerlimit;
	}

	public void setCurrentWarningLowerlimit(BigDecimal currentWarningLowerlimit) {
		this.currentWarningLowerlimit = currentWarningLowerlimit;
	}

	public BigDecimal getSingleHighVolThreshold() {
		return singleHighVolThreshold;
	}

	public void setSingleHighVolThreshold(BigDecimal singleHighVolThreshold) {
		this.singleHighVolThreshold = singleHighVolThreshold;
	}

	public BigDecimal getSingleLowVolThreshold() {
		return singleLowVolThreshold;
	}

	public void setSingleLowVolThreshold(BigDecimal singleLowVolThreshold) {
		this.singleLowVolThreshold = singleLowVolThreshold;
	}

	public BigDecimal getHighVolRecover() {
		return highVolRecover;
	}

	public void setHighVolRecover(BigDecimal highVolRecover) {
		this.highVolRecover = highVolRecover;
	}

	public BigDecimal getLowVolRecover() {
		return lowVolRecover;
	}

	public void setLowVolRecover(BigDecimal lowVolRecover) {
		this.lowVolRecover = lowVolRecover;
	}

	public BigDecimal getSingleHighVolRecover() {
		return singleHighVolRecover;
	}

	public void setSingleHighVolRecover(BigDecimal singleHighVolRecover) {
		this.singleHighVolRecover = singleHighVolRecover;
	}

	public BigDecimal getSingleLowVolRecover() {
		return singleLowVolRecover;
	}

	public void setSingleLowVolRecover(BigDecimal singleLowVolRecover) {
		this.singleLowVolRecover = singleLowVolRecover;
	}

	public Integer getHighSurroundingtemWarningThreshold() {
		return highSurroundingtemWarningThreshold;
	}

	public void setHighSurroundingtemWarningThreshold(Integer highSurroundingtemWarningThreshold) {
		this.highSurroundingtemWarningThreshold = highSurroundingtemWarningThreshold;
	}

	public Integer getLowSurroundingtemWarningThreshold() {
		return lowSurroundingtemWarningThreshold;
	}

	public void setLowSurroundingtemWarningThreshold(Integer lowSurroundingtemWarningThreshold) {
		this.lowSurroundingtemWarningThreshold = lowSurroundingtemWarningThreshold;
	}

	public Integer getHighSurroundingtemWarningRecover() {
		return highSurroundingtemWarningRecover;
	}

	public void setHighSurroundingtemWarningRecover(Integer highSurroundingtemWarningRecover) {
		this.highSurroundingtemWarningRecover = highSurroundingtemWarningRecover;
	}

	public Integer getLowSurroundingtemWarningRecover() {
		return lowSurroundingtemWarningRecover;
	}

	public void setLowSurroundingtemWarningRecover(Integer lowSurroundingtemWarningRecover) {
		this.lowSurroundingtemWarningRecover = lowSurroundingtemWarningRecover;
	}

	public Integer getHightemWarningRecover() {
		return hightemWarningRecover;
	}

	public void setHightemWarningRecover(Integer hightemWarningRecover) {
		this.hightemWarningRecover = hightemWarningRecover;
	}

	public Integer getLowtemWarningRecover() {
		return lowtemWarningRecover;
	}

	public void setLowtemWarningRecover(Integer lowtemWarningRecover) {
		this.lowtemWarningRecover = lowtemWarningRecover;
	}

	public Integer getLowSocRecover() {
		return lowSocRecover;
	}

	public void setLowSocRecover(Integer lowSocRecover) {
		this.lowSocRecover = lowSocRecover;
	}
}